### ISSUE TITLE
Error: Too many errors reported by JSHint.

### ISSUE THREAD

**Issue by deepfriedmind** [addyosmani/sublime-fixmyjs#9]
```
error: FixMyJS
Error: 
/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/fixmyjs.js:22
        throw err;
              ^
Error: Too many errors reported by JSHint.
    at Function.Fix.tme (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:445:15)
    at Code.fix (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:28:21)
    at Object.errors.(anonymous function) [as E043] (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:517:19)
    at fixError (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:539:28)
    at /Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:550:9
    at Array.forEach (native)
    at Object.api.run (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/fixmyjs/lib/legacy.js:711:21)
    at /Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/fixmyjs.js:16:38
    at Socket.<anonymous> (/Users/[USERNAME]/Library/Application Support/Sublime Text 3/Packages/FixMyJS/node_modules/get-stdin/index.js:12:3)
    at Socket.emit (events.js:117:20)
```

This is shown in a dialog box when running FixMyJS on a file where JSHint has given up after too many errors. Selecting a few lines of code that JSHint has a problem with and running FixMyJs does nothing and doesn't output anything to the console. I'm also using SublimeLinter.

**Comment by hivre** [comment]
can confirm that this happens,
Running Ubuntu 15.04/64bit, latest ST3

**Comment by hadifarnoud** [comment]
same here, an error about errors.

**Comment by alzalabany** [comment]
same..

**Comment by fitnr** [comment]
same

**Comment by Gimmo** [comment]
same....

**Comment by MichaelPlaxico** [comment]
. . . Looks like this error is still around. Any plans to remove it? It's pretty useless.

**Comment by davmillar** [comment]
I received this error and tried updating my .jshintrc file to allow more errors to be shown:

    "maxerr": 10000,

The error message no longer appears, but the utility does not seem to perform the fixes or put anything in the console.

**Comment by kongdd** [comment]
> I received this error and tried updating my .jshintrc file to allow more errors to be shown:
> 
> ```
> "maxerr": 10000,
> ```
> The error message no longer appears, but the utility does not seem to perform the fixes or put anything in the console.

Which one .jshintrc file? There are many.
